### ISSUE TITLE
Cannot find the output files

### ISSUE THREAD

**Issue by evatosco** [TopGene/AIvar#1]
Hello there,

when I execute -t predict or -t model with their attributes and correct input & output paths, it processes the data pretty quickly, says "Done" but when I look for output files I cannot find them - same thing with example and with original data.
Could it be a bug, or am I missing something?

Thanks in advance!

PS: using Ubuntu 19.10 & input with exact databases with ANNOVAR, as required in the documentation.

**Comment by TopGene** [comment]
Hi there,

Could you upload the exact code that you executed?

**Comment by evatosco** [comment]
After trying to cover the lack of tensorflow dependencies from previous warnings and logs, I have tried to run aivar again. I do not know if I did it right, though.

Here is the code I used. I have been using some variables and I can confirm they are only paths to files, and that they are correct.

`python3 ./AIVAR.py \
-t predict -m ./bin/AIVAR.model_weights.h5 \
-i $ANNOTATEDVCF \
-o $OUTPUT`

Here is also the output log, attached. 
Now I get to see some results -- 3 files: .AIVAR.result.txt, .AIVAR.result.txt.score and .gnum.txt -- but probability scores are separated from .gnum.txt, where all variants are represented. I need some orientation when it comes to how to know which variant has its corresponding score.

Thank you in advance.

[log.log](https://github.com/TopGene/AIvar/files/5233099/log.log)

**Comment by LuoPangpang** [comment]
Hello,

The .gnum.txt is a file transformed from the annovar annotation file, which is used as an input to the machine learning programme. The human-readable output is the .result.txt and the .score.; the .result.txt gives only 0/1 telling the final prediction of the variant, while .score gives the exact probability that the model predicts.
